CREATE TABLE [dbo].[APODERADO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Nombre] NCHAR(50) NOT NULL, 
    [telefono] NCHAR(50) NOT NULL, 
    [Id_alumno] INT NOT NULL, 
    CONSTRAINT [FK_APODERADO_ALUMNO] FOREIGN KEY ([Id_alumno]) REFERENCES [ALUMNO]([Id]) 
)
